fix: add read me file, manual test and fix type
SAP/ui5-language-assistant pull request #648
Opened 2023-08-10 08:58 UTC by mr25mr

This PR address
* readme file
* Adapt property binding info manual test
* small correction for ArrayType which can be `UI5Typedef`

2023-08-10 09:06 UTC, vinayhospete approved these changes

2023-08-10 09:20 UTC, MN-public requested changes

2023-08-10 09:20 UTC, MN-public commented on packages/vscode-ui5-language-assistant/README.md
> +  - any keys of property binding info
Do we need "any" here? Please also start with the capital letter to follow the pattern above

2023-08-10 09:20 UTC, MN-public commented on packages/vscode-ui5-language-assistant/README.md
> +Property binding info or aggregation binding is semantically highlighted.
Property binding info and aggregation binding are displayed semantically highlighted to let you easily grasp the sense of dense code.
Note: Make sure that semantic highlighting is enabled. For more information, see [[Enablement of semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#enablement-of-semantic-highlighting)

2023-08-10 09:20 UTC, MN-public commented on packages/vscode-ui5-language-assistant/README.md
> +### Semantic highlighting for property binding info or aggregation binding
### Semantic Highlighting

2023-08-10 14:43 UTC, MN-public requested changes

2023-08-10 14:43 UTC, MN-public commented on packages/vscode-ui5-language-assistant/README.md
> +### Semantic Highlighting for property binding info or aggregation binding
I would remove everything after Semantic Highlighting here

2023-08-11 11:44 UTC, MN-public approved these changes

2023-08-11 12:49 UTC, merged